version: '3.8'

services:
  # Эмулятор свитчей
  switch-emulator:
    build: .
    container_name: switch-emulator
    environment:
      - MQTT_BROKER=tcp://emqx:1883
      - REDIS_HOST=redis:6379
      - KAFKA_BROKER=kafka:9093
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=secure_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_DB=device_db
    depends_on:
      - emqx
      - redis
      - kafka
      - postgres
    networks:
      - lighting-net
    restart: always  # Перезапуск контейнера при сбое

  # EMQX - MQTT брокер
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    environment:
      - EMQX_LISTENER__TCP__DEFAULT=1883
    ports:
      - "1883:1883"   # MQTT
      - "18083:18083" # Web UI для EMQX
    networks:
      - lighting-net
    restart: always

  # Redis - кэш
  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=redis_secure_pass_123
    ports:
      - "6379:6379"
    networks:
      - lighting-net
    restart: always

  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093  # Для контейнеров внутри сети
      - KAFKA_LISTENER_PORT=9093
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT
    ports:
      - "9093:9093"  # Проброс порта 9093 для подключения изнутри сети
    depends_on:
      - zookeeper
    networks:
      - lighting-net
    restart: always

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_PASSWORD=zookeeper_pass_123
    ports:
      - "2181:2181"
    networks:
      - lighting-net
    restart: always

  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: secure_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: device_db
    ports:
      - "5432:5432"
    networks:
      - lighting-net
    restart: always

networks:
  lighting-net:
    driver: bridge
