version: "3.8"

services:
  # Эмулятор свитчей
  switch-emulator:
    build: .
    container_name: switch-emulator
    environment:
      - MQTT_BROKER=tcp://emqx:1883
      - REDIS_HOST=redis:6379
      - KAFKA_BROKER=kafka:9092
      - POSTGRES_HOST=postgres:5432
    depends_on:
      - emqx
      - redis
      - kafka
      - postgres
    networks:
      - lighting-net

  # EMQX - MQTT брокер
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"   # MQTT
      - "18083:18083" # Web UI для EMQX
    networks:
      - lighting-net

  # Redis - кэш
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - lighting-net

  # Kafka
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENER: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT_INSIDE: 9093
      KAFKA_LISTENER_INTER_BROKER: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER: INSIDE
      KAFKA_LISTENER_PORT: 9093
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - lighting-net

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - lighting-net

  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: device_db
    ports:
      - "5432:5432"
    networks:
      - lighting-net

networks:
  lighting-net:
    driver: bridge
