services:
  switch-emulator:
    build: .
    container_name: switch-emulator
    environment:
      - MQTT_BROKER=tcp://emqx:1883
      - REDIS_HOST=redis:6379
      - KAFKA_BROKER=kafka:9093
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=secure_user
      - POSTGRES_PASSWORD=secure_password_123
      - POSTGRES_DB=device_db
    depends_on:
      - emqx
      - redis
      - kafka
      - postgres
    networks:
      - lighting-net
    restart: always

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    environment:
      - EMQX_LISTENER__TCP__DEFAULT=1883
    ports:
      - "1883:1883"   # MQTT
      - "18083:18083" # Web UI для EMQX
    networks:
      - lighting-net
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=redis_secure_pass_123
    ports:
      - "6379:6379"
    networks:
      - lighting-net
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_PASSWORD=zookeeper_pass_123
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    networks:
      - lighting-net
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: secure_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: device_db
    ports:
      - "5432:5432"
    networks:
      - lighting-net
    restart: always

networks:
  lighting-net:
    driver: bridge

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-log:
 
